### ISSUE TITLE
History Screen is blank - shows only "Loading data from server"

### ISSUE THREAD

**Issue by rjsears** [ecleese/plexWatchWeb#135] opened 2015-06-11 23:37 UTC
Running the latest dev branch and the history tab only shows a blank screen (no history information) with a note that it is: "Loading data from server".

This was prior to updating to the latest dev branch:
![screen shot 2015-06-11 at 4 03 21 pm](https://cloud.githubusercontent.com/assets/12837199/8120778/0366fb00-1058-11e5-8d7a-4b82172964b4.png)

This was after updating to the latest dev branch:
![screen shot 2015-06-11 at 3 59 43 pm](https://cloud.githubusercontent.com/assets/12837199/8120780/0ba3afca-1058-11e5-88fd-40592018567f.png)

**Comment by Arcanemagus** [comment] 2015-06-11 23:38
Can you open the developer console (Ctrl + Shift + I) and reload the page to see if it is spitting out any javascript errors?

**Comment by rjsears** [comment] 2015-06-11 23:50
Yep - here is what it spit out:

history.php:165 Uncaught SyntaxError: missing ) after argument list

**Comment by timrettop** [comment] 2015-06-12 02:14
Hmm, by the looks of it, that is the sAjaxSource,  is it possible there is a open parens in the oDb serialized data?   Or would the single quote take care of that.  

@rjsears, could you check like 165 on that page and provide it here?

**Comment by rjsears** [comment] 2015-06-12 02:18
Not sure what you are asking @timrettop - Do you want me to copy line 165 from the history.php file and paste it here or...?

**Comment by timrettop** [comment] 2015-06-12 02:19
Yeah, sorry I wasn't clear.

**Comment by rjsears** [comment] 2015-06-12 02:19
FriendlyName.source = JSON.parse('{"saracannonhoover":"Sara Hoover","rsears":"Richard Sears","sammy308":"Sammy Reese","bdavis008":"Becky Davis","desertmansd":"Ted Petrina","rsears+plex for vizio (vizio mtk)":"Rick Creighton","rsears+dana's i pad":"Dana Hoover iPad","smpxone":"Ryan Miller","rsears+office":"RJS Home Office","rsears+plex for sony (playstation 4 01.17)":"Ryan Miller","bphoover":"Bill Hoover","rsears+my sm-t330nu":"Freddie Manuel","rsears+darryl's ipad":"Darryl Hoover iPad","logan700":"Logan Stuard"}');

**Comment by rjsears** [comment] 2015-06-12 02:21
The above is from the output of Chrome. (CMD+Option+J).

The actual history.php file does not have 165 lines, only 157 lines (/var/www/plexwatchweb/history.php

**Comment by rjsears** [comment] 2015-06-12 02:21
Here is 161 through 172:
 
    		
<script type="text/javascript">
function FriendlyName(user) {
  if (!FriendlyName.hasOwnProperty('source')) {
    FriendlyName.source = JSON.parse('{"saracannonhoover":"Sara Hoover","rsears":"Richard Sears","sammy308":"Sammy Reese","bdavis008":"Becky Davis","desertmansd":"Ted Petrina","rsears+plex for vizio (vizio mtk)":"Rick Creighton","rsears+dana's i pad":"Dana Hoover iPad","smpxone":"Ryan Miller","rsears+office":"RJS Home Office","rsears+plex for sony (playstation 4 01.17)":"Ryan Miller","bphoover":"Bill Hoover","rsears+my sm-t330nu":"Freddie Manuel","rsears+darryl's ipad":"Darryl Hoover iPad","logan700":"Logan Stuard"}');
  }
  if (FriendlyName.source.hasOwnProperty(user.toLowerCase())) {
    return FriendlyName.source[user.toLowerCase()];
  } else {
    return user;
  }
}

**Comment by timrettop** [comment] 2015-06-12 02:23
Yeah, its because server datapdatapdo.php is called in history.php generating more output than the original file. 

was there supposed to be more in your last comment, I only see the one line.

**Comment by rjsears** [comment] 2015-06-12 02:26
Yes, I put line 165 up a few comments above as that is where it said the error was, then I also put lines 161 - 172. But the spacing was kind of messed up a bit.

**Comment by Arcanemagus** [comment] 2015-06-12 03:04
So that line is part of my "dirty hack" of outputting the json_encode()'d friendly name database and then parsing that in the javascript to get the database into the client side code...

Can you go to line 173 in serverdatapdo.php and after that put `var_dump($friendlyname_json);` so it should look like:
```php
        }
        $friendlyName_json = json_encode($friendlyName);
var_dump($friendlyName_json);
        /* Edit Jqeury Here */
        $js=  <<<EOT
```
If you load up history.php after that it should put a bunch of junk into the page (and the table will probably be broken). Right click on the page-> View source and copy the line that has all that output in it.

Either paste it here or look over it yourself to make sure that it is properly escaping any ' marks in there. I'll see if I can reproduce the issue on my side.

**Comment by Arcanemagus** [comment] 2015-06-12 03:09
Reproduced it here, looking into what it will take to get PHP's json_encode() to behave.

**Comment by Arcanemagus** [comment] 2015-06-12 03:19
Checkout the latest dev branch, that should fix things for you. Sorry about that!

Closing for now, please re-open if the issue is still present on your setup.

**Closed** 2015-06-12 03:19 UTC
Labels: bug

**Comment by rjsears** [comment] 2015-06-12 13:37
Problem Solved. Thank You @Arcanemagus
